(self.AMP=self.AMP||[]).push({n:"amp-geo",v:"2102130314001",m:0,f:(function(AMP,_){
'use strict';var f="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function g(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}g(this);"function"===typeof Symbol&&Symbol("x");var h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}h=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=h,t;function u(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function v(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var w=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function x(a){var b=Object.create(null);if(!a)return b;for(var c;c=w.exec(a);){var d=v(c[1],c[1]),e=c[2]?v(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var y="";
function D(a){var b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=x(b.location.originalHash||b.location.hash);var d=x(b.location.search);y||(y=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012102130314001");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(c.development)||b.AMP_DEV_MODE),examiner:"2"==c.development,esm:!1,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=d.amp_lite,test:!1,log:c.log,version:"2102130314001",rtvVersion:y};c=b.__AMP_MODE=c}return c}
;var E=Object.prototype.toString;var F=self.AMP_CONFIG||{},G=("string"==typeof F.cdnProxyRegex?new RegExp(F.cdnProxyRegex):F.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function H(a){if(!self.document||!self.document.head||self.location&&G.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var I={thirdParty:F.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:F.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof F.thirdPartyFrameRegex?new RegExp(F.thirdPartyFrameRegex):F.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:F.cdnUrl||H("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:G,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:F.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:F.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:F.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:F.geoApiUrl||H("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var J=self.__AMP_LOG;function K(){if(!J.user)throw Error("failed to call initLogConstructor");return J.user}function L(){if(J.dev)return J.dev;throw Error("failed to call initLogConstructor");};function M(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return N(a,b)}function O(a){a=P(a);a=P(a);a=a.isSingleDoc()?a.win:a;return Q(a,"url")?N(a,"url"):null}function P(a){return a.nodeType?M((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function N(a,b){Q(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function Q(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function R(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};var S={"preset-eea":"AT BE BG HR CY CZ DK EE FI FR DE GR HU IS IE IT LV LI LT LU MT NL NO PL PT RO SK SI ES SE GB AX IC EA GF PF TF GI GP GG JE MQ YT NC RE BL MF PM SJ VA WF EZ CH".split(" "),"preset-us-ca":["us-ca"]};(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0});function aa(a){return!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary)};function ba(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};var ca=/amp-iso-country-(\w+)/,T=/^(?:(\w{2})(?:\s(\w{2}-\w{2}))?)?\s*/;function U(a){a=AMP.BaseElement.call(this,a)||this;a.l=0;a.B=!1;a.h="unknown";a.A="unknown";a.j=[];a.o=[];return a}var V=AMP.BaseElement;U.prototype=f(V.prototype);U.prototype.constructor=U;if(r)r(U,V);else for(var W in V)if("prototype"!=W)if(Object.defineProperties){var X=Object.getOwnPropertyDescriptor(V,W);X&&Object.defineProperty(U,W,X)}else U[W]=V[W];U.C=V.prototype;U.prerenderAllowed=function(){return!0};
U.prototype.buildCallback=function(){var a=this.element.children;a.length&&Y(1===a.length&&R(a[0]),'amp-geo can only have one <script type="application/json"> child');a=a.length?ba(a[0].textContent,function(){return Y(!1,"amp-geo Unable to parse JSON")}):{};var b=da(this,a||{});Z.resolve(b)};function Y(a,b){return a?a:(Z.resolve(null),K().assert(a,b,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0,void 0))}
function ea(a,b){var c=b.getBody().className.match(ca),d=T.exec("ca                          ");if(D(a.win).geoOverride&&aa(a.win)){var e=T.exec(D(a.win).geoOverride.toLowerCase());e[1]&&(a.h=e[1].toLowerCase(),e[2]&&(a.A=e[2].toLowerCase()),a.l=2)}else c&&!O(a.element).isProxyOrigin(a.win.location)?(a.l=1,a.h=c[1]):d[1]?(a.l=0,a.h=d[1].toLowerCase(),d[2]&&"us-ca"===d[2].toLowerCase()&&(a.A="us-ca")):""===d[0]&&I.geoApi?a.l=3:""===d[0]&&(a.B=!0,L().error("amp-geo","GEONOTPATCHED: amp-geo served unpatched, ISO country not set"));
3!==a.l?(t||(t=Promise.resolve(void 0)),b=t):b=fa(a).then(function(l){if(l){var m=l.country,k=l.subdivision;a.h=m;k&&"us-ca"===m+"-"+k&&(a.A="us-ca")}else a.B=!0,L().error("amp-geo","GEONOTPATCHED: amp-geo served unpatched and API response not valid, ISO country not set")});return b}function ha(a){var b=I.geoApi;return"string"!==typeof b?(K().error("amp-geo","geoApiUrl must be a string URL"),null):O(a.element).isSecure(b)?b:(K().error("amp-geo","geoApiUrl must be secure (https)"),null)}
function fa(a){var b=ha(a);if(!b)return Promise.resolve(null);K().info("amp-geo","API request is being used for country, this may result in FOUC");return N(a.win,"timer").timeoutPromise(6E4,M(a.win,"xhr").fetchJson(b,{mode:"cors",method:"GET",credentials:"omit"}).then(function(c){return c.json()}).then(function(c){return/^[a-z]{2}$/i.test(c.country)?{country:c.country.toLowerCase(),subdivision:/^[a-z0-9]{1,3}$/i.test(c.subdivision)?c.subdivision.toLowerCase():null}:(K().error("amp-geo",'Invalid API response, expected schema not matched for property "country"'),
null)}).catch(function(c){K().error("amp-geo","XHR country request failed",c);return null}),"Timeout (60 sec) reached waiting for API response").catch(function(c){K().error("amp-geo",c);return null})}
function ia(a,b){var c=b.ISOCountryGroups;c&&(Y("[object Object]"===E.call(c),"<amp-geo> ISOCountryGroups must be an object"),a.o=Object.keys(c),a.o.forEach(function(d){Y(/^[a-z]+[a-z0-9]*$/i.test(d)&&!/^amp/.test(d),"<amp-geo> ISOCountryGroups["+d+"] name is invalid");Y(Array.isArray(c[d]),"<amp-geo> ISOCountryGroups["+d+"] must be an array");ja(a,c[d])&&a.j.push(d)}))}
function ja(a,b){var c=b.reduce(function(d,e){if(/^preset-/.test(e))return Y(Array.isArray(S[e]),"<amp-geo> preset "+e+" not found"),d.concat(S[e]);"unknown"==e||/^[a-zA-Z]{2}$/.test(e)?d.push(e):K().error("amp-geo"," country %s not valid, will be ignored",e);return d},[]).map(function(d){return d.toLowerCase()});return c.includes(a.h)||c.includes("us-ca")&&"us-ca"==a.A}
function ka(a){var b=a.classList,c=[],d=/^amp-iso-country-|^amp-geo-group-/i;for(a=b.length-1;0<a;a--)d.test(b[a])&&c.push(b[a]);return c}
function da(a,b){var c=a.getAmpDoc(),d={};return c.whenReady().then(function(){return c.waitForBodyOpen()}).then(function(e){return ea(a,c).then(function(){return e})}).then(function(e){ia(a,b);var l=[];switch(a.l){case 2:l=ka(e);case 0:case 3:d.ISOCountry=a.h;var m=a.j.map(function(k){d[k]=!0;return"amp-geo-group-"+k});a.j.length||m.push("amp-geo-no-group");a.B&&m.push("amp-geo-error");d.ISOCountryGroups=a.j;m.push("amp-iso-country-"+a.h);a.mutateElement(function(){var k=e.classList;l.push("amp-geo-pending");
l.forEach(function(z){k.remove(z)});m.forEach(function(z){return k.add(z)});if(b.AmpBind){var A=c.getElementById("ampGeo");A&&A.parentNode.removeChild(A);var B=c.win.document.createElement("amp-state"),C=c.win.document.createElement("script");C.setAttribute("type","application/json");C.textContent=JSON.stringify(d);B.appendChild(C);B.id="ampGeo";e.appendChild(B)}},e)}return{ISOCountry:a.h,matchedISOCountryGroups:a.j,allISOCountryGroups:a.o,isInCountryGroup:a.isInCountryGroup.bind(a)}})}
U.prototype.isInCountryGroup=function(a){var b=this,c=a.trim().split(/,\s*/);return c.filter(function(d){return 0<=b.o.indexOf(d)}).length!==c.length?1:0<c.filter(function(d){return 0<=b.j.indexOf(d)}).length?2:3};var Z=null;(function(a){Z=new u;a.registerElement("amp-geo",U);a.registerServiceForDoc("geo",function(){return Z.promise})})(self.AMP);
})});

//# sourceMappingURL=amp-geo-0.1.js.map
